In [4]:
from PIL import Image
import numpy as np

# 1. Load the image
img = Image.open('ss.png')

# 2. Convert it to a NumPy array
img_array = np.array(img)

# 3. View the shape (Height, Width, 3 color channels)
print(img_array.shape) 

# 4. View the raw pixel numbers of the first pixel
# print(img_array[0, 0])  # Outputs something like: [255, 
print(img_array)

(744, 1040, 4)
[[[ 14  13  14 255]
  [ 14  13  14 255]
  [ 14  13  14 255]
  ...
  [ 14  15  16 255]
  [ 14  15  16 255]
  [ 14  15  16 255]]

 [[ 14  13  14 255]
  [ 14  13  14 255]
  [ 14  13  15 255]
  ...
  [ 14  15  16 255]
  [ 14  15  16 255]
  [ 14  15  16 255]]

 [[ 14  13  14 255]
  [ 14  13  14 255]
  [ 14  13  15 255]
  ...
  [ 14  15  16 255]
  [ 14  15  16 255]
  [ 14  15  16 255]]

 ...

 [[ 14  18  26 255]
  [ 14  18  26 255]
  [ 14  18  26 255]
  ...
  [  1   5  13 255]
  [  1   5  13 255]
  [  2   6  14 255]]

 [[ 14  18  26 255]
  [ 14  18  26 255]
  [ 14  18  26 255]
  ...
  [  1   5  13 255]
  [  1   5  13 255]
  [  2   6  14 255]]

 [[ 14  18  26 255]
  [ 14  18  26 255]
  [ 14  18  26 255]
  ...
  [  1   5  13 255]
  [  1   5  13 255]
  [  0   4  12 255]]]
